---
- name: windows install all updates and reboot  
  hosts: all
  tasks:
  - name: Install all updates (if any), log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names: "*"
      state: installed
      reboot: yes
      reboot_timeout: 3600 
      log_path: C:\ansible_wu.txt