---
- name: windows updates for security, critical, rollup with no reboots 
  hosts: all
  tasks:
  - name:  Search all security, critical, rollup updates, and log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: searched
      log_path: C:\ansible_wu.txt

  - name:  Download all security, critical, rollup updates, and log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: downloaded
      log_path: C:\ansible_wu.txt

  - name:  Install all security, critical, rollup updates, and log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: installed
      reboot: yes
      reboot_timeout: 3600
      log_path: C:\ansible_wu.txt