---
- name: windows updates 
  hosts: all
  tasks:
  - name: Install all updates (if any), log to C:\ansible_wu.txt
    ansible.windows.win_updates:
      category_names: "*"
      state: installed
      reboot: true
      reboot_timeout: 1800 
      log_path: C:\ansible_wu.txt