---
- name: win_reboot module 
  hosts: MMS-015000-L 
  become: false 
  gather_facts: false 
  tasks:
    - name: reboot host(s)
      ansible.windows.win_reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 10
        post_reboot_delay: 15 